---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 4 # Устанавливаем 4 реплики для обеспечения отказоустойчивости и возможности справляться с пиковой нагрузкой
  strategy:
    type: RollingUpdate # Используем стратегию RollingUpdate для плавного обновления подов, минимизируя время простоя
    rollingUpdate:
      maxSurge: 1 # Разрешаем создание одного дополнительного пода сверх желаемого количества при обновлении
      maxUnavailable: 1 # Разрешаем недоступность одного пода во время обновления, что помогает поддерживать доступность
  selector:
    matchLabels:
      app: web-app # Определяем метку, которая будет использоваться для выбора подов этого развертывания
  template:
    metadata:
      labels:
        app: web-app # Метки, которые будут применяться к подам, создаваемым этим развертыванием
    spec:
      containers:
      - name: web-app-container
        image: web-app:latest # Образ контейнера приложения
        resources:
          requests:
            memory: "128Mi" # Минимальные запрашиваемые ресурсы памяти для каждого пода
            cpu: "0.1" # Минимальные запрашиваемые ресурсы CPU для каждого пода
          limits:
            memory: "128Mi" # Максимальное использование памяти (равно запросу, поскольку потребление постоянное)
            cpu: "1" # Максимально допустимое использование CPU (выше, чтобы покрыть пики загрузки при инициализации)
        livenessProbe:
          httpGet:
            path: /healthz # Путь для проверки работоспособности контейнера
            port: 8080
          initialDelaySeconds: 30 # Задержка перед началом проверок работоспособности, чтобы дать приложению время на инициализацию
          periodSeconds: 10 # Интервал между проверками работоспособности
        readinessProbe:
          httpGet:
            path: /ready # Путь для проверки готовности контейнера к приему запросов
            port: 8080
          initialDelaySeconds: 30 # Задержка перед началом проверок готовности, чтобы приложение успело запуститься
          periodSeconds: 10 # Интервал между проверками готовности

